name: Deploy to Google Artifact Registry on push

on:
  push:
    branches:
      - main
      - develop

env:
  GAR_LOCATION: europe-north1
  GAR_PROJECT_ID: qbi-infra
  GAR_REPOSITORY: qbi-prod

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      -
        name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      -
        name: Build and push
        run: |
          image_name="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GAR_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ github.event.repository.name }}"
          image_tag=$([ "${{ github.ref_name }}" = "main" ] && echo "production" || echo "staging")
          docker build . -t "$image_name:$image_tag"
          if [ $image_tag = "production" ]; then
            docker tag "$image_name" "$image_name:latest"
          fi
          docker push "$image_name" --all-tags
